# Generated by Django 2.2.3 on 2019-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email_address', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('native_language', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
    ]
