# Generated by Django 2.2.3 on 2019-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('display_name', models.CharField(blank=True, max_length=225, null=True)),
                ('email_address', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_id', models.CharField(blank=True, max_length=50, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('native_language', models.CharField(blank=True, max_length=20, null=True)),
                ('cost_model_type', models.CharField(blank=True, max_length=10, null=True)),
                ('cost_model_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('total_working_cities', models.IntegerField(blank=True, null=True)),
                ('total_working_places', models.IntegerField(blank=True, null=True)),
                ('total_completes_trips', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
    ]
